---
function:
  name: omni-wt-cw-lenovo-create-shipment-${self:provider.stage}
  handler: src/create-shipment/Lenovo/index.handler
  memorySize: 2048
  timeout: 900
  layers:
    - !Ref NodeModulesLambdaLayer
  package:
    patterns:
      - '!**/*'
      - src/create-shipment/Lenovo/*
      - src/shared/*
  events:
    - s3:
        bucket: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
        existing: true
        events:
          - s3:ObjectCreated:*
        rules:
          - prefix: ${ssm:/${self:service}/${self:provider.stage}/s3-prefix}
          - suffix: ${ssm:/${self:service}/${self:provider.stage}/s3-suffix}

  environment:
    WT_URL: ${ssm:/omni-dw/${self:provider.stage}/createShipment/wt/url}
    CW_URL: ${ssm:/omni-wt-cw-integration/${self:provider.stage}/createShipment/cw/url}
    CW_ENDPOINT_AUTHORIZATION: ${ssm:/omni-wt-cw-integration/${self:provider.stage}/createShipment/cw/auth}
    LOGS_TABLE: ${ssm:/omni-wt-cw-integration/${self:provider.stage}/create-shipment-status-table-name}
    wt_soap_username: ${ssm:/omni-dw/${self:provider.stage}/wt/soap/username}
    wt_soap_password: ${ssm:/omni-dw/${self:provider.stage}/wt/soap/password}
